implement valhalla's trace_attributes
gis-ops/routing-py pull request #73
Opened 2022-07-18 16:21 UTC by nilsnolde

WIP

2022-07-19 14:18 UTC, nilsnolde commented on routingpy/routers/valhalla.py
> +            **kwargs
kwargs didn't really exist before here either

2022-07-19 14:19 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +class MatchType(str, Enum):
these are fixed enums for response entries

2022-07-19 14:20 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +class MatchedEdge:
this is a single edge object with most interesting properties set. could be extended in future, but good enough for NA

2022-07-19 14:20 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +class MatchedPoint:
same for matched points

2022-07-19 14:21 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +class MatchedResults:
this is what the user will get. he can then go through the `matched_edges` and `matched_points` lists

2022-07-19 14:22 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +            ]
begin/end_shape_index can be empty for first/last edge :roll_eyes:

2022-07-25 07:06 UTC, chrstnbwnkl requested changes
Almost good to go, just one faulty condition and a docstring that needs a small update

2022-07-25 07:06 UTC, chrstnbwnkl commented on CHANGELOG.md
> +- Added Valhalla's trace_attributes endpoint
Shouldn't this be listed under `added`?

2022-07-25 07:06 UTC, chrstnbwnkl commented on routingpy/routers/valhalla.py
> +        """Gets the expansion tree for a range of time or distance values around a given coordinate.
copied expansion docstring

2022-07-31 20:11 UTC, nilsnolde commented on routingpy/valhalla_attributes.py
> +        elif point.get("begin_route_discontinuity"):
good catch!

2022-08-08 06:38 UTC, merged